### PR TITLE
Open generics

### PR DESCRIPTION
**Pull request by cheng93**
Solution for #172

### CODE REVIEW

**Comment by cheng93** [comment]
@jeremydmiller I've added/adjusted the unit tests based on what I think the behaviour will be.

If you agree, I will attempt to finish this PR when I have time.

**Comment by jeremydmiller** [comment]
@cheng93 Can you rebase this on master?

**Comment by cheng93** [comment]
@jeremydmiller Rebased

**Comment by cheng93** [comment]
won't have time

**Pull request closed without merging**
