### PR TITLE
Adding unit test for scoped instances being shared across threads

### PR DESCRIPTION
**Pull request by matthawley**
Failing unit tests for bug #173

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@matthawley I'm looking at this today finally

**Comment by jsheetzati** [comment]
Could this explain why I am having issues with DbContext in asp.net core 3? See frequent exceptions like 
`A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext` or `Invalid operation. The connection is closed.`

Coming from asp.net core 2.2 with StructureMap where we do not have this issue. I searched for usual culprits in our code like async voids but not coming up with anything. Could very well be something else but this PR stuck out to me as a possible explanation.

**Comment by matthawley** [comment]
@jsheetzati If you look at the related bug, it was closed it as non reproducible. We ultimately removed Lamar and our issues went away. I can't say for sure that it's the same, but if you're attempting to get a scoped object from a transient object, it's quite possible - as that was our scenario.

**Comment by jeremydmiller** [comment]
@jsheetzati I tried the repro steps again today from this PR and I cannot reproduce the issue. Wanna try a different PR with reproduction steps using EF? The other time we had a bug something like this it did turn out to be something in the Expression model, but I would want to see reproduction steps that actually trip off a failure before I try changing anything

**Pull request closed without merging**
